services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/catalogdb
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=catalogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d catalogdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
