version: "3.9"

services:
  mini-pg:
    image: postgres:15-alpine
    container_name: mini-pg
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d catalogdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"   # UI
      - "1025:1025"   # SMTP

  api:
    build: .
    container_name: mini-datacatalog-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://localhost:8000/healthz', timeout=3)\n  sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: dev@mini.local
      ERROR_NOTIFY_TO: dev@mini.local
      PG_URL: postgresql+psycopg2://admin:admin@mini-pg:5432/catalogdb
    depends_on:
      mini-pg:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - .:/app
    command: >
      uvicorn fastapi_app:app --host 0.0.0.0 --port 8000
      --reload
      --reload-exclude ".venv/*"
      --reload-exclude "logs/*"

volumes:
  pgdata:
