services:
  api:
    build: .
    container_name: mini-datacatalog-api
    ports:
      - "8000:8000"
    # .env فعلی‌ات را می‌خوانیم
    env_file:
      - .env
    # ولی برای توسعه، SMTP را به MailHog override می‌کنیم
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: dev@mini.local
      ERROR_NOTIFY_TO: dev@mini.local
      SMTP_STARTTLS: "false"

    volumes:
      - .:/app
    command: >
      uvicorn fastapi_app:app
      --host 0.0.0.0 --port 8000
      --reload
      --reload-exclude "/app/.venv/*"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"   # وب‌ UI
      - "1025:1025"   # SMTP
