name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Wait for PostgreSQL
        run: |
          # این اسکریپت با استفاده از nc (netcat) منتظر می‌مونه تا پورت 5432 دیتابیس باز بشه
          for i in `seq 1 10`; do
            nc -z db 5432 && echo "PostgreSQL is ready!" && break
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      
      - name: Run tests
        env:
          DATABASE_URL: postgresql://test_user:test_password@db:5432/test_db
        run: |
          python -m pytest -v